openapi: 3.0.3

info:
  title: Web File Browser API
  version: 1.0.0

paths:
  /child:
    post:
      tags:
        - comment
      summary: getChildren
      description: Operation gets all children of directory or archive
      operationId: getChilds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetFileRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilesResponse'
        400:
          $ref: '#/components/responses/Error'
        422:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

components:

  responses:

    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:

    GetFileRequest:
      type: object
      required:
        - path
      properties:
        path:
          $ref: '#/components/schemas/Path'

    FileInfo:
      description: File information
      type: object
      required:
        - path
        - name
        - type
      properties:
        path:
          $ref: '#/components/schemas/Path'
        name:
          description: Name
          type: string
          example: work
        type:
          description: Type
          type: string
          enum: [ file, directory, archive ]
          example: directory

    Path:
      description: Absolute path
      type: string
      example: "Users/i.ivanov/Documents/work"

    GetFilesResponse:
      type: array
      items:
        $ref: '#/components/schemas/FileInfo'

    ErrorResponse:
      description: Error with message
      type: object
      required:
        - message
      properties:
        message:
          description: Message
          type: string
          example: File 'props' is not a dicrectory or archive
